**ASSIGNMENT ON DATA FILTERING**

##TASK
Analyze the fashion store dataset using filtering and subsetting to extract the product name, color, and brand name for products with a cost price between 10.00 and 30.00.

In [3]:
import pandas as pd

my_data=r'c:\Users\MURERWA DANIEL\Downloads\dataset_fashion_store_products.csv'
df=pd.read_csv(my_data)
df.head()

,product_id,product_name,category,brand,color,size,catalog_price,cost_price,gender
0,1,Soft Wrap Dress,Dresses,Tiva,Green,S,40.41,20.70,Female
1,2,Soft Wrap Tee,T-Shirts,Tiva,White,S,78.45,53.76,Female
2,3,Soft Linen Tee,T-Shirts,Tiva,Green,XL,23.90,14.81,Female
3,4,Soft Ribbed Tee,T-Shirts,Tiva,White,S,60.00,34.78,Female
4,5,Soft Wrap Trousers,Pants,Tiva,Blue,M,36.84,16.46,Female

In [20]:
#filtering the data for the proce range or 10 and 30
df_filtered=df[(df['cost_price']>=10.00) & (df['cost_price']<=30.00)]
df_filtered[['product_name', 'color','brand']]

                     product_name  color brand
0                 Soft Wrap Dress  Green  Tiva
2                  Soft Linen Tee  Green  Tiva
4              Soft Wrap Trousers   Blue  Tiva
6                Soft Linen Dress  White  Tiva
8                Soft Linen Shoes    Red  Tiva
..                            ...    ...   ...
495  Tailored High-Waist Trousers  Black  Tiva
496                Dresses Drop 8  Black  Tiva
497               T-Shirts Drop 8  White  Tiva
498              Sleepwear Drop 4  Green  Tiva
499                Dresses Drop 9  White  Tiva

[313 rows x 3 columns]

In [19]:
#subsetting the data to get the product name, color, and brand name
df_subset = df_filtered[['product_name', 'color', 'brand']]
df_subset

                     product_name  color brand
0                 Soft Wrap Dress  Green  Tiva
2                  Soft Linen Tee  Green  Tiva
4              Soft Wrap Trousers   Blue  Tiva
6                Soft Linen Dress  White  Tiva
8                Soft Linen Shoes    Red  Tiva
..                            ...    ...   ...
495  Tailored High-Waist Trousers  Black  Tiva
496                Dresses Drop 8  Black  Tiva
497               T-Shirts Drop 8  White  Tiva
498              Sleepwear Drop 4  Green  Tiva
499                Dresses Drop 9  White  Tiva

[313 rows x 3 columns]