#### Learning Objectives 

##### *Understand what data wrangling is and why it is important* -> Done

##### *Perform basic data wrangling tasks like handling missing values*

##### *Subset datasets using columns & rows*

##### *Have a sense of how to use Python to wrangle and subset real world data*

##### *Technical Definition of Data Wrangling*

Data wrangling, also known as data munging or data preparation, is the process of cleaning, structuring, and transforming raw data into a usable format for analysis and other data-driven applications. It addresses issues like missing values, inconsistencies, and duplicates to ensure data quality and make it more consumable

Data wrangling, sometimes referred to as data munging, is the process of transforming and mapping data from one "raw" data form into another format with the intent of making it more appropriate and valuable for a variety of downstream purposes such as analytics. The goal of data wrangling is to assure quality and useful data. Data analysts typically spend the majority of their time in the process of data wrangling compared to the actual analysis of the data.

In [1]:
# Cleaning
# Structuring
# Transformation
# Data Quality

##### *An Intuitive Explanation of Data Warangling*

In [2]:
# Raw data == Messy ingredients in your kitchen
# Cook == Analyze
# Before Cooking == Clean, Slice, Organize, etc.
# What is Data Wrangling? == Steps before you are ready to cook

##### *Usecase Explanations*

In [3]:
# Theres a movement from paper registrations to paperless registration - Health
# All paper registrations where transfered to spreadsheets
# A health Analysts (Domain knowledge) need to clean the patients records because there's 
# missing and inconsistent data

In [4]:
# Clean data for a real estate problem

In [5]:
# Machine Learning == Inputs + Model + Outputs
# Analyze data to prep for modeling

#### Set Things UP

In [6]:
import pandas as pd

In [7]:
# Sample data
sample_data = {
    'Name': ['Alice', 'Bob', 'Charles', None, 'Eve'],
    'Age': [25, None, -35, 45, 29],
    'Gender': ['F', 'M', 'M', 'M', 'F'],
    'Country': ['Nigeria', 'Kenya', 'Nigeria', 'Ghana', 'Nigeria']
}

In [8]:
type(sample_data)

dict

In [9]:
# Create our dataframe
df = pd.DataFrame(sample_data)
df.head()

      Name   Age Gender  Country
0    Alice  25.0      F  Nigeria
1      Bob   NaN      M    Kenya
2  Charles -35.0      M  Nigeria
3     None  45.0      M    Ghana
4      Eve  29.0      F  Nigeria

##### *Data is shared with the immigration Analyst*

In [10]:
df

      Name   Age Gender  Country
0    Alice  25.0      F  Nigeria
1      Bob   NaN      M    Kenya
2  Charles -35.0      M  Nigeria
3     None  45.0      M    Ghana
4      Eve  29.0      F  Nigeria

In [11]:
# Concise summary of the data
?df.info

Signature:
df.info(
    verbose: 'bool | None' = None,
    buf: 'WriteBuffer[str] | None' = None,
    max_cols: 'int | None' = None,
    memory_usage: 'bool | str | None' = None,
    show_counts: 'bool | None' = None,
) -> 'None'
Docstring:
Print a concise summary of a DataFrame.

This method prints information about a DataFrame including
the index dtype and columns, non-null values and memory usage.

Parameters
----------
verbose : bool, optional
    Whether to print the full summary. By default, the setting in
    ``pandas.options.display.max_info_columns`` is followed.
buf : writable buffer, defaults to sys.stdout
    Where to send the output. By default, the output is printed to
    sys.stdout. Pass a writable buffer if you need to further process
    the output.
max_cols : int, optional
    When to switch from the verbose to the truncated output. If the
    DataFrame has more than `max_cols` columns, the truncated output
    is used. By default, the setting in
    ``pandas.options.display.max_info_columns`` is used.
memory_usage : bool, str, optional
    Specifies whether total memory usage of the DataFrame
    elements (including the index) should be displayed. By default,
    this follows the ``pandas.options.display.memory_usage`` setting.

    True always show memory usage. False never shows memory usage.
    A value of 'deep' is equivalent to "True with deep introspection".
    Memory usage is shown in human-readable units (base-2
    representation). Without deep introspection a memory estimation is
    made based in column dtype and number of rows assuming values
    consume the same memory amount for corresponding dtypes. With deep
    memory introspection, a real memory usage calculation is performed
    at the cost of computational resources. See the
    :ref:`Frequently Asked Questions <df-memory-usage>` for more
    details.
show_counts : bool, optional
    Whether to show the non-null counts. By default, this is shown
    only if the DataFrame is smaller than
    ``pandas.options.display.max_info_rows`` and
    ``pandas.options.display.max_info_columns``. A value of True always
    shows the counts, and False never shows the counts.

Returns
-------
None
    This method prints a summary of a DataFrame and returns None.

See Also
--------
DataFrame.describe: Generate descriptive statistics of DataFrame
    columns.
DataFrame.memory_usage: Memory usage of DataFrame columns.

Examples
--------
>>> int_values = [1, 2, 3, 4, 5]
>>> text_values = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
>>> float_values = [0.0, 0.25, 0.5, 0.75, 1.0]
>>> df = pd.DataFrame({"int_col": int_values, "text_col": text_values,
...                   "float_col": float_values})
>>> df
    int_col text_col  float_col
0        1    alpha       0.00
1        2     beta       0.25
2        3    gamma       0.50
3        4    delta       0.75
4        5  epsilon       1.00

Prints information of all columns:

>>> df.info(verbose=True)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   int_col    5 non-null      int64
 1   text_col   5 non-null      object
 2   float_col  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes

Prints a summary of columns count and its dtypes but not per column
information:

>>> df.info(verbose=False)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 3 entries, int_col to float_col
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes

Pipe output of DataFrame.info to buffer instead of sys.stdout, get
buffer content and writes to a text file:

>>> import io
>>> buffer = io.StringIO()
>>> df.info(buf=buffer)
>>> s = buffer.getvalue()
>>> with open("df_info.txt", "w",
...           encoding="utf-8") as f:  # doctest: +SKIP
...     f.write(s)
260

The `memory_usage` parameter allows deep introspection mode, specially
useful for big DataFrames and fine-tune memory optimization:

>>> random_strings_array = np.random.choice(['a', 'b', 'c'], 10 ** 6)
>>> df = pd.DataFrame({
...     'column_1': np.random.choice(['a', 'b', 'c'], 10 ** 6),
...     'column_2': np.random.choice(['a', 'b', 'c'], 10 ** 6),
...     'column_3': np.random.choice(['a', 'b', 'c'], 10 ** 6)
... })
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   column_1  1000000 non-null  object
 1   column_2  1000000 non-null  object
 2   column_3  1000000 non-null  object
dtypes: object(3)
memory usage: 22.9+ MB

>>> df.info(memory_usage='deep')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   column_1  1000000 non-null  object
 1   column_2  1000000 non-null  object
 2   column_3  1000000 non-null  object
dtypes: object(3)
memory usage: 165.9 MB
File:      c:\users\murerwa daniel\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Age      4 non-null      float64
 2   Gender   5 non-null      object
 3   Country  5 non-null      object
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

##### *Handle the missing values*

In [13]:
df['Name'] = df['Name'].fillna('Grid Loss')

In [14]:
df

        Name   Age Gender  Country
0      Alice  25.0      F  Nigeria
1        Bob   NaN      M    Kenya
2    Charles -35.0      M  Nigeria
3  Grid Loss  45.0      M    Ghana
4        Eve  29.0      F  Nigeria

In [15]:
# Indexer (loc/iloc)

In [16]:
df.iloc[2, 1] = 'Grid Loss' # Position based indexing

C:\Users\MURERWA DANIEL\AppData\Local\Temp\ipykernel_2780\622556726.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Grid Loss' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[2, 1] = 'Grid Loss' # Position based indexing

In [17]:
df

        Name        Age Gender  Country
0      Alice       25.0      F  Nigeria
1        Bob        NaN      M    Kenya
2    Charles  Grid Loss      M  Nigeria
3  Grid Loss       45.0      M    Ghana
4        Eve       29.0      F  Nigeria

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      4 non-null      object
 2   Gender   5 non-null      object
 3   Country  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

##### *Changing data types*

In [19]:
#df['Age'] = df['Age'].astype(float)

In [20]:
# To solve
import numpy as np
pd.set_option('future.no_silent_downcasting', True)

In [21]:
df['Age'] = df['Age'].replace(['Grid Loss'], np.nan)

In [22]:
df

        Name   Age Gender  Country
0      Alice  25.0      F  Nigeria
1        Bob   NaN      M    Kenya
2    Charles   NaN      M  Nigeria
3  Grid Loss  45.0      M    Ghana
4        Eve  29.0      F  Nigeria

##### *Focus on what we need*

In [23]:
# Sselect specific columns
df_demo = df[['Name', 'Age', 'Country']]

In [24]:
df_demo

        Name   Age  Country
0      Alice  25.0  Nigeria
1        Bob   NaN    Kenya
2    Charles   NaN  Nigeria
3  Grid Loss  45.0    Ghana
4        Eve  29.0  Nigeria

In [25]:
# Select based on rows
df_ngr = df[df['Country'] == 'Nigeria']

In [26]:
df['Country'] == 'Nigeria' # Boolean Output

0     True
1    False
2     True
3    False
4     True
Name: Country, dtype: bool

In [27]:
df_ngr

      Name   Age Gender  Country
0    Alice  25.0      F  Nigeria
2  Charles   NaN      M  Nigeria
4      Eve  29.0      F  Nigeria

#### Consider this real data

In [28]:
house_data=r"C:\Users\MURERWA DANIEL\Documents\GitHub\DataScience\Data_Dataset\housing_data.csv"
house_data = pd.read_csv(house_data)
house_data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [29]:
# Subsetted based on columns

In [30]:
house_data_sub = house_data[['Id','MSSubClass','MSZoning','LotFrontage','LotArea']]

KeyError: "None of [Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea'], dtype='object')] are in the [columns]"

In [ ]:
house_data_sub.head()

In [ ]:
# Subset based on rows
house_data_sub20 = house_data_sub[house_data_sub['MSSubClass']== 20]

In [ ]:
house_data_sub20.head()

#### Data Wrangling & Filtering

#### Learning Objectives

##### *Understand Data Wrangling & Filtering (Contextually)* - Done

##### *Use the Pandas Module to Filter Data* - Done

##### *Understand the business case for filtering Data* - Done

##### *Filtering*

In [ ]:
# It is a process of subsetting rows based on Boolean conditions
# It allows us to focus on relevant data for data analysis and visualization

##### *Use cases*

In [ ]:
# HR & Recruitment Analytics: 
# Filter employees or Job seekers based on some conditions
# Business Value: Employee Management & Talent Recruitment

In [ ]:
# Marketing Analytics: 
# Filtering for target customers based on buying psychology/Demographics 
# Business Value: Profit/Sales/High Conversion targets

In [ ]:
# Retail Analytics: 
# Inventory of Product Status
# Business Value: Reodering logic/model for just-in-time inventory

In [ ]:
# Financial Analytic: 
# Audit Transactions for certain Thresholds 
# Business Value: Fraud Detection & Financial Compliance

In [ ]:
# Health Analytics:
# Tracking Patient Visits
# Business Value: Build model for reminders

In [ ]:
import pandas as pd # Data Manipulation Library

In [ ]:
# Create Mock Data
student_data = {
        'student name': ['Precious Ayoola', 'Praise Sanni', 'Yao Theodore', 'Olivier Dusabamahoro', 'Daniel Murerwa'],
        'City': ['Lagos', 'Kaduna', 'Lome', 'Kigali', 'Nairobi'],
        'Age': [23, 21, 25, 20, 22],
        'Score': [88, 92, 76, 65, 99]
}

In [ ]:
df = pd.DataFrame(student_data)
df

In [ ]:
# Filter rows for scores
df['Score'] >= 90

In [ ]:
df[df['Score'] >= 90]

In [ ]:
df_90 = df[df['Score'] >= 90]

In [ ]:
# Filter for City
df['City'] == 'Kigali'

In [ ]:
df[df['City'] == 'Kigali']

In [ ]:
# Filter for city and score
# City - Lagos & Score > 70

In [ ]:
df['City'] == 'Lagos'

In [ ]:
df['Score'] > 70

In [ ]:
(df['City'] == 'Lagos') & (df['Score'] > 70)

In [ ]:
df[(df['City'] == 'Lagos') & (df['Score'] > 70)]

In [ ]:
#(df['City'] == 'Lagos') and (df['Score'] > 70)

In [ ]:
# Filter for people from Lagos or Nairobi
['Lagos', 'Nairobi']

In [ ]:
df['City']

In [ ]:
# .isin

In [ ]:
df['City'].isin(['Lagos', 'Nairobi'])

In [ ]:
df[df['City'].isin(['Lagos', 'Nairobi'])]

In [ ]:
# Filter for rows where names contain the letter a
# a is case-sensitive

In [ ]:
df['student name']

In [ ]:
# contains 'a'
df['student name'].str.contains('d', case=False)

In [ ]:
df[df['student name'].str.contains('d', case=False)]

##### *Why is filtering Important?*

In [ ]:
# Large data easier to digest
# Focuses on relevant insights
# Improve decision-making speed

##### *Retail Analtics (Fashion)*

In [32]:
!head dataset_fashion_store_products.csv

head: cannot open `dataset_fashion_store_products.csv' for reading: No such file or directory

In [33]:
fashionStore_data = pd.read_csv('dataset_fashion_store_products.csv')
fashionStore_data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_fashion_store_products.csv'

In [ ]:
# Filter for Size
fashionStore_data['size'] == 'S'

In [ ]:
fashionStore_data[fashionStore_data['size'] == 'S'].head()

In [ ]:
fashionStore_data_small = fashionStore_data[fashionStore_data['size'] == 'S']

In [ ]:
fashionStore_data_small.head(20)

In [ ]:
fashionStore_data_small['color'].value_counts()

In [ ]:
fashionStore_data_small['category'].value_counts()

In [ ]:
# Filter for colors blue, green & red
['Green', 'Blue', 'Red']

In [ ]:
color_pref_kids = fashionStore_data_small[fashionStore_data_small['color'].isin(['Green', 'Blue', 'Red'])]

In [ ]:
color_pref_kids.head()

In [ ]:
color_pref_kids['gender'].value_counts()

#### Assignment 

##### Using the fashion store dataset, employ subsetting and filtering to extract

##### the product name, color and brand name of products with cost price between 

##### 10.00 to 30.00


###### *Submission instructions: Submit the Jupyter notebook inside the message thread* 
###### *where I share the 2nd live class notebook in our community platform*

###### *Submission Deadline: July 17, 11:59pm*

###### *Deadlines are firm*

###### *Dataset: https://drive.google.com/file/d/12553vFFFSyFv9TYDQXK6zSYg_DVZXyJh/view?usp=sharing*

#### Data Aggregation

#### Learning Objectives 

##### *Understand the intuition behind data aggregation* Done

##### *Understand how to aggregate data using the Pandas groupby function* Done

##### *Understand how to aggregate using a dataset* Done

##### *Technical Definition*

Data aggregation is a process of applying summary statistics to grouped subsets of data.

This is done using the Pandas groupby method

##### *Non-Technical Definition*

Grouping similar things together and summarizing them so its easire to understand

##### *Why is data aggregation important in real-world problem solving?*

In [ ]:
# Retail usecase -> Summarize product/store sales
# Public Policy usecase -> Group data for income analysis, gender for equity analysis 
# Group by demographies to understand poverty distributions 
# Group by locations to understand food insecurities 
# Group by location to understand disease breakout
# Logistic Usecase - Group by cities to understand delivery challenges

##### *A simple example of a groupby function*

In [ ]:
# Create a simple dataframe
import pandas as pd

In [ ]:
data = {
    'Store Location': ['Lagos', 'Lagos', 'Abuja', 'Abuja', 'Kano'],
    'Product': ['Bread', 'Milk', 'Bread', 'Milk', 'Bread'],
    'Sales': [100, 200, 150, 250, 50]
}

In [ ]:
df = pd.DataFrame(data)
df

##### *For a store location, what is their total sales?*

In [ ]:
?df.groupby

In [ ]:
df.groupby('Store Location')['Sales']

In [ ]:
df.groupby('Store Location')['Sales'].sum()

##### *Other Aggregation Functions*

.sum()

.mean()

.median()

.count()

.max()/min()

.agg()

In [ ]:
df.groupby('Store Location')['Sales'].agg(['sum', 'mean', 'count'])

##### *Why do we summarize data?*

1. Quick Insights

2. Raw data to informed decisions

3. Unsual Trends

4. Data Reduction for clarity

5. Data Visualization

In [ ]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

#### Use groupby on a dataset

In [ ]:
housing_data = pd.read_csv('house_data.csv')
house_data.head()

##### *Are house prices increasing or decreasing by year?*

In [ ]:
# Year Sold
# House Price

In [31]:
house_data.groupby('YrSold')['SalePrice'].mean()

KeyError: 'YrSold'

In [ ]:
house_data.groupby('YrSold')['SalePrice'].median()

##### *Do land size increase based on housing zones?*

In [ ]:
house_data['MSZoning'].head()

In [ ]:
# Feature Transformation 
house_data['MSZoning'].unique()

In [ ]:
zoning_housing = {"RL": "Residential Low Density",
"RM": "Residential Medium Density",
"C (all)": "Commercial",
"FV": "Floating Village Residential",
"RH": "Floating Village Residential"}

In [ ]:
house_data['Zone Identifier'] = house_data['MSZoning'].replace(zoning_housing)

In [ ]:
house_data.head()

In [ ]:
house_data['Zone Identifier'].value_counts(normalize=True)

In [ ]:
house_data['LotArea'].head()

In [ ]:
# Groupby function
house_data.groupby('Zone Identifier')['LotArea'].median()

In [ ]:
house_data.groupby('Zone Identifier')['LotArea'].agg(['median', 'mean', 'sum'])

##### *Sales based on zones*

In [ ]:
house_data.groupby('Zone Identifier')['SalePrice'].agg(['mean', 'median', 'count'])

##### *Can we group by more than one feature?*

##### *Average sale price based on year sold & zone*

In [ ]:
house_data.groupby(['YrSold', 'Zone Identifier'])['SalePrice'].median()