Learning Data Wrangling
Basic Data Wrangling
Subset datasets using columns and rows
How to use Python to wrangle and subset real world data

Data Cleaning
Structuring
Trnasformation
Data Quality

Raw Data ==Messy ingridients in your kitchn
cook==analyze
before cooking==clean,slice,organize, etc

wrangling==steps before you are ready to cook

UseCase Explanations

cleaning patient records

In [34]:
#Settind things up
import pandas as pd
sample_data={
    'Name':['Alice', 'Bob', 'Charlie', 'David', 'Eve',''],
    'Age':[25, 30, 35, -25, 0, 45],
    'Gende':['female', 'male', 'male', 'male','female', 'null'],
    'Country':['USA', 'Canada', 'UK', 'Uganda', 'Canada', 'Uganda'],

}
df=pd.DataFrame(sample_data)
type(df)
df.head(10)

      Name  Age   Gende Country
0    Alice   25  female     USA
1      Bob   30    male  Canada
2  Charlie   35    male      UK
3    David  -25    male  Uganda
4      Eve    0  female  Canada
5            45    null  Uganda

In [35]:
#Handling Missing Values
df['Name']=df['Name'].fillna('Grid Loss')
df.head(10)

      Name  Age   Gende Country
0    Alice   25  female     USA
1      Bob   30    male  Canada
2  Charlie   35    male      UK
3    David  -25    male  Uganda
4      Eve    0  female  Canada
5            45    null  Uganda

In [36]:
df.iloc[5,0]='Grid Loss'
df.head(10)

        Name  Age   Gende Country
0      Alice   25  female     USA
1        Bob   30    male  Canada
2    Charlie   35    male      UK
3      David  -25    male  Uganda
4        Eve    0  female  Canada
5  Grid Loss   45    null  Uganda

In [37]:
df_demo=df[['Name', 'Age', 'Country']]
df_demo

        Name  Age Country
0      Alice   25     USA
1        Bob   30  Canada
2    Charlie   35      UK
3      David  -25  Uganda
4        Eve    0  Canada
5  Grid Loss   45  Uganda

In [38]:
df['Country']=='Uganda'

0    False
1    False
2    False
3     True
4    False
5     True
Name: Country, dtype: bool

In [41]:
df_ug=df['Country']=='Uganda'
df_ug

0    False
1    False
2    False
3     True
4    False
5     True
Name: Country, dtype: bool

In [42]:
datas=r'C:\Users\MURERWA DANIEL\Documents\GitHub\DataScience\Data_Dataset\housing.csv'
df1=pd.read_csv(datas)
df1.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY