Data Wrangling and Filtering

Objectives
1. understand data wrangling and filtering(Contextualy)
2. use the pandas module to filter data
3. understand the business case for filtering data

Filterin
    process of subsetting rows based on boolean conditions
    it allows to focus on relevant data for analysis and visualization

Use cases
    HR and recruitment Analytics
    Filter employees or job seekers based on some conditions
    Business value: employee management and talent recruitment

    Market Analytics:
        filtering for target customers based in buying psychology/demographics
        
    Business Value:
        Profit/sales/high conversion targets

    Retail Analytics:
        Inventory of product status
        business value-rordering model

    Financial Analytics:
        audit transcations for certain thresholds
        business value-fraud detection and financial compliance

    Health Analytics
        Tracking Patient visits
        business value-build model for reminders

In [16]:
import pandas as pd # Data manipulation library

In [17]:
#create a mocking dataframe
student_data={
    'student_name':['John Mark', 'Precious Jane', 'Mark James Doe', 'olivia Grace', 'Daniel Murerwa'],
    'city':['Lagos', 'Kaduma', 'Lome', 'Kigali', 'Nairobi'],
    'age':[23, 21, 25, 20, 22],
    'scores':[85, 90, 78, 88, 92],
    }

In [18]:
df=pd.DataFrame(student_data)
df.head() # Display the first few rows of the DataFrame

     student_name     city  age  scores
0       John Mark    Lagos   23      85
1   Precious Jane   Kaduma   21      90
2  Mark James Doe     Lome   25      78
3    olivia Grace   Kigali   20      88
4  Daniel Murerwa  Nairobi   22      92

In [19]:
#filteing rows for scores
df['scores']>85

0    False
1     True
2    False
3     True
4     True
Name: scores, dtype: bool

In [20]:
df['age']>25

0    False
1    False
2    False
3    False
4    False
Name: age, dtype: bool

In [21]:
df[df['scores']>=90]

     student_name     city  age  scores
1   Precious Jane   Kaduma   21      90
4  Daniel Murerwa  Nairobi   22      92

In [22]:
df_90=df[df['scores']>=90]
df['city']=='Kigali'

0    False
1    False
2    False
3     True
4    False
Name: city, dtype: bool

In [23]:
#filter for city and scores
#city is lagos and scores is greater than  70
df['city']=='Lagos' 
df['scores']>70

0    True
1    True
2    True
3    True
4    True
Name: scores, dtype: bool

In [28]:
(df['city']=='Lagos') & (df['scores'] > 70)

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [50]:
df[(df['city']=='Lagos') & (df['scores'] > 70)]

  student_name   city  age  scores
0    John Mark  Lagos   23      85

In [ ]:
df[(df['city']=='Lagos') and (df['scores'] > 70)]

In [ ]:
#filter for people from lagos and nairobi
['Lagos', 'Nairobi']


df['city']

0      Lagos
1     Kaduma
2       Lome
3     Kigali
4    Nairobi
Name: city, dtype: object

In [32]:
df['city'].isin(['Lagos', 'Nairobi'])

0     True
1    False
2    False
3    False
4     True
Name: city, dtype: bool

In [33]:
df[df['city'].isin(['Lagos', 'Nairobi'])]

     student_name     city  age  scores
0       John Mark    Lagos   23      85
4  Daniel Murerwa  Nairobi   22      92

Get dataset and try get the insights or filter the data for understading

In [36]:
#filter for the rows with letter a
#letter 'a' is case sensitive
df['student_name']

0         John Mark
1     Precious Jane
2    Mark James Doe
3      olivia Grace
4    Daniel Murerwa
Name: student_name, dtype: object

In [45]:
df['student_name'].str.contains('r', case=False)  # Case-insensitive search for 'r'

0    True
1    True
2    True
3    True
4    True
Name: student_name, dtype: bool

In [47]:
df[df['student_name'].str.contains('w', case=False)]

     student_name     city  age  scores
4  Daniel Murerwa  Nairobi   22      92

Why is filtering important

    large dara us easier to digest
    focuseson relevant insights
    improve decision-making speed

In [52]:
#Ecommerce dataset
commerce_data=r'C:\Users\MURERWA DANIEL\Documents\GitHub\DataScience\Data_Dataset\ecomerce data\dataset_fashion_store_products.csv'
df_commrce=pd.read_csv(commerce_data)
df_commrce.head()

,product_id,product_name,category,brand,color,size,catalog_price,cost_price,gender
0,1,Soft Wrap Dress,Dresses,Tiva,Green,S,40.41,20.70,Female
1,2,Soft Wrap Tee,T-Shirts,Tiva,White,S,78.45,53.76,Female
2,3,Soft Linen Tee,T-Shirts,Tiva,Green,XL,23.90,14.81,Female
3,4,Soft Ribbed Tee,T-Shirts,Tiva,White,S,60.00,34.78,Female
4,5,Soft Wrap Trousers,Pants,Tiva,Blue,M,36.84,16.46,Female

In [60]:
#filter by size
df_commrce[df_commrce['size']=='S'].head()

,product_id,product_name,category,brand,color,size,catalog_price,cost_price,gender
0,1,Soft Wrap Dress,Dresses,Tiva,Green,S,40.41,20.70,Female
1,2,Soft Wrap Tee,T-Shirts,Tiva,White,S,78.45,53.76,Female
3,4,Soft Ribbed Tee,T-Shirts,Tiva,White,S,60.00,34.78,Female
14,15,Soft Cotton Tee,T-Shirts,Tiva,Blue,S,61.26,27.85,Female
18,19,Soft Silk Dress,Dresses,Tiva,Blue,S,65.26,34.56,Female

In [62]:
#filter by color
df_commrce['color'].value_counts()

color
Black    104
Green    102
Blue     102
Red       98
White     94
Name: count, dtype: int64

In [63]:
#filter for category
df_commrce['category'].value_counts()

category
Dresses      109
T-Shirts     108
Sleepwear    104
Shoes        100
Pants         79
Name: count, dtype: int64

In [69]:
#filter for colors blue green and red
kids_color=df_commrce[df_commrce['color'].isin(['Blue', "Green", 'Red'])]
kids_color.head()

,product_id,product_name,category,brand,color,size,catalog_price,cost_price,gender
0,1,Soft Wrap Dress,Dresses,Tiva,Green,S,40.41,20.70,Female
2,3,Soft Linen Tee,T-Shirts,Tiva,Green,XL,23.90,14.81,Female
4,5,Soft Wrap Trousers,Pants,Tiva,Blue,M,36.84,16.46,Female
5,6,Soft Wrap Shoes,Shoes,Tiva,Green,36,70.86,31.66,Female
7,8,Soft Linen Trousers,Pants,Tiva,Green,M,50.91,33.59,Female

In [79]:

df_commrce[(df_commrce['catalog_price']>80) & (df_commrce['category']=='Dresses')]

,product_id,product_name,category,brand,color,size,catalog_price,cost_price,gender
402,403,Elegant Satin Dress,Dresses,Tiva,Red,L,81.8,45.12,Female

In [81]:
#filter for gender
kids_color['gender'].value_counts()

gender
Female    302
Name: count, dtype: int64