***Learning Objective***

**Detect Outliers using statistical imputation**

**Use an EDA workflow**

**Use Visualization to detect outliers**

In [40]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [41]:
housin_data=r'C:\Users\MURERWA DANIEL\Documents\GitHub\DataScience\Data_Dataset\housing_data.csv'
df=pd.read_csv(housin_data)
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [42]:
#as a DS at a real estate start-up
#you are to buiild a model that predicts the price of a house
#we need to extract outliers from the dataset

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

**Pipelining**

In [44]:
df_1=df.copy()

In [45]:
df_1.drop(['area_type', 'availability', 'society', 'balcony'], axis='columns', inplace=True)

df_1.head(1)

                   location   size total_sqft  bath  price
0  Electronic City Phase II  2 BHK       1056   2.0  39.07

In [46]:
df_1.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [47]:
df_2=df_1.copy()

In [48]:
df_2.dropna(inplace=True)
df_2.isna().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [49]:
#Evaluate column features in DF
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13246 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13246 non-null  object
 1   size        13246 non-null  object
 2   total_sqft  13246 non-null  object
 3   bath        13246 non-null  float64
 4   price       13246 non-null  float64
dtypes: float64(2), object(3)
memory usage: 620.9+ KB

In [50]:
#evaluate the size column
df_2['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [51]:
#what does BHK mean?
#BHK means Bedroom, Hall, Kitchen

#Feature engineer the size column and create a new column called bhk

df_2['bhk']=df_2['size'].apply(lambda x: int(x.split(" ")[0]))
df_2.head(10)

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2
5                Whitefield      2 BHK       1170   2.0   38.00    2
6          Old Airport Road      4 BHK       2732   4.0  204.00    4
7              Rajaji Nagar      4 BHK       3300   4.0  600.00    4
8              Marathahalli      3 BHK       1310   3.0   63.25    3
9              Gandhi Bazar  6 Bedroom       1020   6.0  370.00    6

**New Pipeline**

In [52]:
df_3=df_2.copy()

In [53]:
#evaluate total_sqft column
df_3['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [54]:
#convert all the values in the total_sqft column to float
#if it's not a float value, let it be

def convert_float(x):
    try:
        float(x)
    except:
        return False
    
    return True

In [55]:
#apply the convert_float function to the total_sqft column
df_3['total_sqft'].apply(convert_float)

0        True
1        True
2        True
3        True
4        True
         ...
13315    True
13316    True
13317    True
13318    True
13319    True
Name: total_sqft, Length: 13246, dtype: bool

In [56]:
df_3[df_3['total_sqft'].apply(convert_float)]

                       location       size total_sqft  bath   price  bhk
0      Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1              Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2                   Uttarahalli      3 BHK       1440   2.0   62.00    3
3            Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                      Kothanur      2 BHK       1200   2.0   51.00    2
...                         ...        ...        ...   ...     ...  ...
13315                Whitefield  5 Bedroom       3453   4.0  231.00    5
13316             Richards Town      4 BHK       3600   5.0  400.00    4
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0   60.00    2
13318           Padmanabhanagar      4 BHK       4689   4.0  488.00    4
13319              Doddathoguru      1 BHK        550   1.0   17.00    1

[13056 rows x 6 columns]

In [57]:
df_3[~df_3['total_sqft'].apply(convert_float)] #negate

                 location   size   total_sqft  bath    price  bhk
30              Yelahanka  4 BHK  2100 - 2850   4.0  186.000    4
122                Hebbal  4 BHK  3067 - 8156   4.0  477.000    4
137    8th Phase JP Nagar  2 BHK  1042 - 1105   2.0   54.005    2
165              Sarjapur  2 BHK  1145 - 1340   2.0   43.490    2
188              KR Puram  2 BHK  1015 - 1540   2.0   56.800    2
...                   ...    ...          ...   ...      ...  ...
12975          Whitefield  2 BHK   850 - 1060   2.0   38.190    2
12990      Talaghattapura  3 BHK  1804 - 2273   3.0  122.000    3
13059              Harlur  2 BHK  1200 - 1470   2.0   72.760    2
13265               Hoodi  2 BHK  1133 - 1384   2.0   59.135    2
13299          Whitefield  4 BHK  2830 - 2882   5.0  154.500    4

[190 rows x 6 columns]

In [58]:
def convert_sqft(x):
    tokens=x.split('-')
    if len(tokens)==2:
        return(float(tokens[0])+float(tokens[1]))/2
    
    try:
        return float(x)
    except:
        return None

In [59]:
convert_sqft('650 - 655')

652.5

In [60]:
df_3['total_sqft']=df_3['total_sqft'].apply(convert_sqft)
df_3.head(30)

                    location       size  total_sqft  bath   price  bhk
0   Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1           Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2                Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3         Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                   Kothanur      2 BHK      1200.0   2.0   51.00    2
5                 Whitefield      2 BHK      1170.0   2.0   38.00    2
6           Old Airport Road      4 BHK      2732.0   4.0  204.00    4
7               Rajaji Nagar      4 BHK      3300.0   4.0  600.00    4
8               Marathahalli      3 BHK      1310.0   3.0   63.25    3
9               Gandhi Bazar  6 Bedroom      1020.0   6.0  370.00    6
10                Whitefield      3 BHK      1800.0   2.0   70.00    3
11                Whitefield  4 Bedroom      2785.0   5.0  295.00    4
12        7th Phase JP Nagar      2 BHK      1000.0   2.0   38.00    2
13                 Gottigere      2 BHK      1100.0   2.0   40.00    2
14                  Sarjapur  3 Bedroom      2250.0   3.0  148.00    3
15               Mysore Road      2 BHK      1175.0   2.0   73.50    2
16             Bisuvanahalli      3 BHK      1180.0   3.0   48.00    3
17     Raja Rajeshwari Nagar      3 BHK      1540.0   3.0   60.00    3
18     Ramakrishnappa Layout      3 BHK      2770.0   4.0  290.00    3
19        Manayata Tech Park      2 BHK      1100.0   2.0   48.00    2
20                   Kengeri      1 BHK       600.0   1.0   15.00    1
21                Binny Pete      3 BHK      1755.0   3.0  122.00    3
22               Thanisandra  4 Bedroom      2800.0   5.0  380.00    4
23                 Bellandur      3 BHK      1767.0   3.0  103.00    3
24               Thanisandra       1 RK       510.0   1.0   25.25    1
25           Mangammanapalya      3 BHK      1250.0   3.0   56.00    3
26           Electronic City      2 BHK       660.0   1.0   23.10    2
27                Whitefield      3 BHK      1610.0   3.0   81.00    3
28          Ramagondanahalli      2 BHK      1151.0   2.0   48.77    2
29           Electronic City      3 BHK      1025.0   2.0   47.00    3

In [61]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13246 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13246 non-null  object
 1   size        13246 non-null  object
 2   total_sqft  13200 non-null  float64
 3   bath        13246 non-null  float64
 4   price       13246 non-null  float64
 5   bhk         13246 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 724.4+ KB

In [64]:
df_4=df_3[df_3['total_sqft'].notnull()]

In [65]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13200 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13200 non-null  object
 1   size        13200 non-null  object
 2   total_sqft  13200 non-null  float64
 3   bath        13200 non-null  float64
 4   price       13200 non-null  float64
 5   bhk         13200 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 721.9+ KB

*Feature engineer the price column*

In [66]:
df_5=df_4.copy()

In [67]:
df_5['price_per_sqft']=df_5['price']*100/df_5['total_sqft']

In [68]:
df_5['price_per_sqft'].head(10)

0     3.699811
1     4.615385
2     4.305556
3     6.245891
4     4.250000
5     3.247863
6     7.467057
7    18.181818
8     4.828244
9    36.274510
Name: price_per_sqft, dtype: float64

In [69]:
df_5.head(10)

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3.699811
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4.615385
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4.305556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6.245891
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4.250000
5,Whitefield,2 BHK,1170.0,2.0,38.00,2,3.247863
6,Old Airport Road,4 BHK,2732.0,4.0,204.00,4,7.467057
7,Rajaji Nagar,4 BHK,3300.0,4.0,600.00,4,18.181818
8,Marathahalli,3 BHK,1310.0,3.0,63.25,3,4.828244
9,Gandhi Bazar,6 Bedroom,1020.0,6.0,370.00,6,36.274510

#Outlier detection#

##bd in India has 300 sqft as normal size##

In [73]:
df_5[df_5['total_sqft']/df_5['bhk']<300].head(10)

,location,size,total_sqft,bath,price,bhk,price_per_sqft
9,Gandhi Bazar,6 Bedroom,1020.0,6.0,370.0,6,36.274510
45,HSR Layout,8 Bedroom,600.0,9.0,200.0,8,33.333333
58,Murugeshpalya,6 Bedroom,1407.0,4.0,150.0,6,10.660981
68,Devarachikkanahalli,8 Bedroom,1350.0,7.0,85.0,8,6.296296
70,Double Road,3 Bedroom,500.0,3.0,100.0,3,20.000000
78,Kaval Byrasandra,2 BHK,460.0,1.0,22.0,2,4.782609
89,Rajaji Nagar,6 Bedroom,710.0,6.0,160.0,6,22.535211
119,Hennur Road,2 Bedroom,276.0,3.0,23.0,2,8.333333
129,Vishwapriya Layout,7 Bedroom,950.0,7.0,115.0,7,12.105263
149,Dinnur,6 Bedroom,1034.0,5.0,185.0,6,17.891683

In [74]:
df_5.shape

(13200, 7)

In [76]:
#remove outliers
df_5[~(df_5['total_sqft']/df_5['bhk']<300)]

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3.699811
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4.615385
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4.305556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6.245891
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4.250000
...,...,...,...,...,...,...,...
13315,Whitefield,5 Bedroom,3453.0,4.0,231.00,5,6.689835
13316,Richards Town,4 BHK,3600.0,5.0,400.00,4,11.111111
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,60.00,2,5.258545
13318,Padmanabhanagar,4 BHK,4689.0,4.0,488.00,4,10.407336
13319,Doddathoguru,1 BHK,550.0,1.0,17.00,1,3.090909

In [78]:
df_6=df_5[~(df_5['total_sqft']/df_5['bhk']<300)]

df_6.shape

(12456, 7)

**Removing Outliers using Statistical Imputation**

In [79]:
#price per Sqft > (mean - std)

#Price per sqft <=(mean + std)

#**Removing Outliers using Statistical Imputation**